"""
render.py: render the sample emails and the funnel scenarios.

Reads data/leads_personalized.csv, config/campaign.yaml, and templates/*.yaml.
Writes output/sample_emails.md (three touches for five representative leads, with
the E1 A/B arm assigned deterministically) and output/funnel_scenarios.csv. Excluded
rows are listed by reason so the filtering shows in the output. No arguments.
"""

import hashlib
from pathlib import Path

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[1]
PERS = ROOT / "data" / "leads_personalized.csv"
CONFIG = ROOT / "config" / "campaign.yaml"
TEMPLATES = ROOT / "templates"
OUT_EMAILS = ROOT / "output" / "sample_emails.md"
OUT_FUNNEL = ROOT / "output" / "funnel_scenarios.csv"

MERGE_FIELDS = ["first_name", "city", "practice_name",
                "nearest_location", "opener", "slots_remaining"]

# The five representative slots to render. Highest priority_score fills each.
SELECTIONS = [
    ("nutrition", "warm", "nutrition, warm, launch market"),
    ("nutrition", "cold", "nutrition, cold, launch market"),
    ("fitness", "warm", "fitness, warm, launch market"),
    ("fitness", "cold", "fitness, cold, launch market"),
    ("clinical", None, "clinical, launch market, either temperature"),
]

# Planning assumptions pulled straight from the strategy memo, section 7.
# Not forecasts. The base case already sits at the referral supply ceiling.
FUNNEL_ROWS = [
    ("Total leads", "1000", "1000", "1000"),
    ("Valid and classified", "850", "850", "850"),
    ("In launch markets sent this campaign", "600", "600", "600"),
    ("Positive reply rate", "6%", "12%", "20%"),
    ("Interested providers", "36", "72", "120"),
    ("Clear vetting and fit", "25", "50", "80"),
    ("Paying at day 90", "8", "20", "35"),
    ("Subscription ARR at $99, excluding referral fees", "~$9.5k", "~$23.8k", "~$41.6k"),
]


def load_templates():
    templates = {}
    for name in ("nutrition", "fitness", "clinical"):
        with open(TEMPLATES / (name + ".yaml")) as f:
            templates[name] = yaml.safe_load(f)
    return templates


def merge(text, lead, link):
    out = str(text)
    for field in MERGE_FIELDS:
        out = out.replace("{" + field + "}", str(lead.get(field, "")))
    out = out.replace("{link}", link)
    return out


def assign_arms(eligible):
    """Sort eligible leads by the SHA256 hash of lead_id, then alternate A and B
    down the sorted list. Deterministic, and the two arms stay within one lead of
    each other. Hash parity only splits evenly on average, so it is not used.
    """
    ordered = sorted(eligible["lead_id"],
                     key=lambda x: hashlib.sha256(x.encode()).hexdigest())
    return {lead_id: ("A" if i % 2 == 0 else "B") for i, lead_id in enumerate(ordered)}


def pick(eligible, profession, temperature):
    subset = eligible[eligible["profession"] == profession]
    if temperature is not None:
        subset = subset[subset["temperature"] == temperature]
    if subset.empty:
        return None
    # Highest priority_score, ties break to the lowest lead_id.
    subset = subset.sort_values(["priority_score", "lead_id"],
                                ascending=[False, True])
    return subset.iloc[0]


def render_email(email, lead, arm_map, link):
    lines = []
    if "subject_variants" in email:
        arm = arm_map[lead["lead_id"]]
        variant = next(v for v in email["subject_variants"] if v["arm"] == arm)
        subject = merge(variant["text"], lead, link)
        lines.append("**Subject (arm {}, testing {}):** {}".format(
            arm, variant["hypothesis"], subject))
    else:
        lines.append("**Subject:** {}".format(merge(email["subject"], lead, link)))
    lines.append("")
    lines.append("```")
    lines.append(merge(email["body"], lead, link).strip())
    lines.append("```")
    return "\n".join(lines)


def main():
    with open(CONFIG) as f:
        config = yaml.safe_load(f)
    link = config.get("application_link", "{link}")
    seq = config["sequence_days"]
    templates = load_templates()

    df = pd.read_csv(PERS, dtype=str, keep_default_na=False)
    df["priority_score"] = df["priority_score"].astype(int)
    eligible = df[df["excluded_reason"] == ""].copy()
    arm_map = assign_arms(eligible)

    out = []
    out.append("# Sample rendered emails")
    out.append("")
    out.append("Generated by `src/render.py` from the committed mock data. "
               "Fifteen emails, three touches each for five representative leads. "
               "The E1 subject arm is assigned deterministically by the hash of "
               "`lead_id`. No excluded or waitlist lead is ever rendered here.")
    out.append("")

    for profession, temperature, label in SELECTIONS:
        lead = pick(eligible, profession, temperature)
        note = ""
        if lead is None:
            # Fall back to the highest priority eligible lead in the same category.
            lead = pick(eligible, profession, None)
            note = (" (no {} lead available, substituted the highest priority "
                    "{} lead)".format(label, profession))
        out.append("---")
        out.append("")
        out.append("## {}{}".format(label, note))
        out.append("")
        out.append("**{first} at {practice}, {city} {state}.** "
                   "Category `{prof}` (confidence {pconf}), temperature `{temp}`, "
                   "priority score `{score}`, personalization confidence `{perc}`."
                   .format(first=lead["first_name"], practice=lead["practice_name"],
                           city=lead["city"], state=lead["state"],
                           prof=lead["profession"], pconf=lead["profession_confidence"],
                           temp=lead["temperature"], score=lead["priority_score"],
                           perc=lead["personalization_confidence"]))
        out.append("")
        for email in templates[profession]["emails"]:
            day = seq[email["id"]]
            out.append("### {} (day {})".format(email["id"].upper(), day))
            out.append("")
            out.append(render_email(email, lead, arm_map, link))
            out.append("")

    # Excluded rows, grouped by reason, so the filtering is visible in the output.
    out.append("---")
    out.append("")
    out.append("## Excluded rows, by reason")
    out.append("")
    out.append("Retained in the dataset, not sent this campaign.")
    out.append("")
    excluded = df[df["excluded_reason"] != ""]
    def bucket(r):
        return "duplicate_of" if r.startswith("duplicate_of") else r
    for reason in sorted(excluded["excluded_reason"].apply(bucket).unique()):
        rows = excluded[excluded["excluded_reason"].apply(bucket) == reason]
        out.append("**{}** ({})".format(reason, len(rows)))
        out.append("")
        for _, r in rows.iterrows():
            detail = r["excluded_reason"] if reason == "duplicate_of" else ""
            suffix = " ({})".format(detail) if detail else ""
            out.append("- `{}` {}, {}, {} {}{}".format(
                r["lead_id"], r["full_name"] or "(no name)", r["job_title"] or "(no title)",
                r["city"] or "(no city)", r["state"], suffix))
        out.append("")

    OUT_EMAILS.write_text("\n".join(out))

    funnel = pd.DataFrame(FUNNEL_ROWS,
                          columns=["stage", "conservative", "base", "upside"])
    funnel.to_csv(OUT_FUNNEL, index=False)

    print("Wrote {} ({} emails across {} leads).".format(
        OUT_EMAILS.name, len(SELECTIONS) * 3, len(SELECTIONS)))
    print("Wrote {}.".format(OUT_FUNNEL.name))
    print("A/B arm split across {} eligible leads: {} A, {} B.".format(
        len(arm_map),
        sum(1 for v in arm_map.values() if v == "A"),
        sum(1 for v in arm_map.values() if v == "B")))


if __name__ == "__main__":
    main()
